[build]
  command = "turbo run clean --filter web && turbo run build --filter web"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
